[supervisord]
nodaemon=true
user=root

[program:murmur]
command=/usr/sbin/murmurd -fg
autorestart=true
user=root

[program:mumble-web]
command=node server/dist/index.js --port 7860 --mumble localhost:64738
autorestart=true
user=root
